### ISSUE TITLE
editions with webpack

### ISSUE THREAD

**Issue by viviancpy** [bevry/editions#8] opened 2016-05-06 01:42 UTC
I use webpack in my project. For unit testing, I used expect-jsx which depends on sortobject and editions. The problem may be due to dynamic require in requirePackage function which cannot be imported well in webpack, and I got 

```
WARNING in ./~/editions/es2015/index.js
Critical dependencies:
101:10-28 the request of a dependency is an expression
```

I tried putting "main": "es2015/index" in my package.json, but still got same errors. 

After some digging into the matter, I have a work-around which is to put in my webpack.unit-test.js to have:
```
resolve: {
       alias: {
          sortobject: path.join(__dirname, '/node_modules/sortobject/es2015/index.js')
        }
}
```

Would like to know how to use package.json if the editions is in vendors code?

**Comment by balupton** [comment] 2016-05-06 03:30
Are you using an old version of webpack? As webpack supports the browser field which sortobject uses.

**Comment by balupton** [comment] 2016-05-10 07:47
Going to close as a dupe of https://github.com/bevry/sortobject/issues/3

**Closed by balupton** 2016-05-10 07:47 UTC
